
/*******************************************************************************
* generated by lcd-image-converter rev.4d43872 from 2022-06-23 22:11:57 +0500
* font
* filename: /home/paco/Arial_LCD_Font.xml
* name: Arial
* family: Inconsolata Extra Expanded
* size: 9
* style: Regular
* included characters:  !"#$%&'()*+,-./0123456789:;<=>?\x0040ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~
* antialiasing: no
* type: monospaced
* encoding: UTF-8
* unicode bom: no
* compacted: no
*
* preset name: Monochrome_Band_Inverted_NB
* data block size: 8 bit(s), uint8_t
* RLE compression enabled: no
* conversion type: Monochrome, Diffuse Dither 128
* split to rows: no
* bits per pixel: 1
*
* preprocess:
*  main scan direction: left_to_right
*  line scan direction: forward
*  inverse: yes
*******************************************************************************/
#include <stdint.h>
#define _NO_EXT_
#include "arial.h"

/*
 typedef struct {
     const uint8_t *data;
     uint16_t width;
     uint16_t height;
     uint8_t dataSize;
     } tImage;
 typedef struct {
     long int code;
     const tImage *image;
     const int image_left;
     const int image_top;
     const int char_width;
     const int char_height;
     } tChar;
 typedef struct {
     int length;
     const tChar *chars;
     } tFont;
*/

#define FIX_ZERO_LENGTH(length) (length==0?1:length)



static const uint8_t image_data_Arial_0x20[FIX_ZERO_LENGTH(8)] = {
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
};
static const tImage Arial_0x20 = { image_data_Arial_0x20,
    0, 0, 8};

static const uint8_t image_data_Arial_0x21[FIX_ZERO_LENGTH(8)] = {
    0x00, 0x00, 0x00, 0xbe, 0x00, 0x00, 0x00, 0x00
};
static const tImage Arial_0x21 = { image_data_Arial_0x21,
    0, 0, 8};

static const uint8_t image_data_Arial_0x22[FIX_ZERO_LENGTH(8)] = {
    0x00, 0x00, 0x0e, 0x00, 0x0e, 0x00, 0x00, 0x00
};
static const tImage Arial_0x22 = { image_data_Arial_0x22,
    0, 0, 8};

static const uint8_t image_data_Arial_0x23[FIX_ZERO_LENGTH(8)] = {
    0x20, 0xe8, 0x3e, 0x28, 0xfe, 0x28, 0x00, 0x00
};
static const tImage Arial_0x23 = { image_data_Arial_0x23,
    0, 0, 8};

static const uint8_t image_data_Arial_0x24[FIX_ZERO_LENGTH(8)] = {
    0x00, 0xc8, 0x94, 0xfe, 0xa4, 0xe8, 0x00, 0x00
};
static const tImage Arial_0x24 = { image_data_Arial_0x24,
    0, 0, 8};

static const uint8_t image_data_Arial_0x25[FIX_ZERO_LENGTH(8)] = {
    0x04, 0xca, 0x2a, 0x5c, 0xa4, 0xa2, 0x40, 0x00
};
static const tImage Arial_0x25 = { image_data_Arial_0x25,
    0, 0, 8};

static const uint8_t image_data_Arial_0x26[FIX_ZERO_LENGTH(8)] = {
    0x40, 0xa4, 0x9a, 0xaa, 0x4c, 0xe0, 0x20, 0x00
};
static const tImage Arial_0x26 = { image_data_Arial_0x26,
    0, 0, 8};

static const uint8_t image_data_Arial_0x27[FIX_ZERO_LENGTH(8)] = {
    0x00, 0x00, 0x00, 0x0e, 0x00, 0x00, 0x00, 0x00
};
static const tImage Arial_0x27 = { image_data_Arial_0x27,
    0, 0, 8};

static const uint8_t image_data_Arial_0x28[FIX_ZERO_LENGTH(8)] = {
    0x00, 0x30, 0x48, 0x84, 0x02, 0x00, 0x00, 0x00
};
static const tImage Arial_0x28 = { image_data_Arial_0x28,
    0, 0, 8};

static const uint8_t image_data_Arial_0x29[FIX_ZERO_LENGTH(8)] = {
    0x00, 0x02, 0x04, 0x84, 0x78, 0x00, 0x00, 0x00
};
static const tImage Arial_0x29 = { image_data_Arial_0x29,
    0, 0, 8};

static const uint8_t image_data_Arial_0x2a[FIX_ZERO_LENGTH(8)] = {
    0x00, 0x28, 0x28, 0x1c, 0x28, 0x08, 0x00, 0x00
};
static const tImage Arial_0x2a = { image_data_Arial_0x2a,
    0, 0, 8};

static const uint8_t image_data_Arial_0x2b[FIX_ZERO_LENGTH(8)] = {
    0x00, 0x10, 0x10, 0x78, 0x10, 0x10, 0x00, 0x00
};
static const tImage Arial_0x2b = { image_data_Arial_0x2b,
    0, 0, 8};

static const uint8_t image_data_Arial_0x2c[FIX_ZERO_LENGTH(8)] = {
    0x00, 0x00, 0x00, 0x80, 0x00, 0x00, 0x00, 0x00
};
static const tImage Arial_0x2c = { image_data_Arial_0x2c,
    0, 0, 8};

static const uint8_t image_data_Arial_0x2d[FIX_ZERO_LENGTH(8)] = {
    0x00, 0x10, 0x10, 0x10, 0x10, 0x00, 0x00, 0x00
};
static const tImage Arial_0x2d = { image_data_Arial_0x2d,
    0, 0, 8};

static const uint8_t image_data_Arial_0x2e[FIX_ZERO_LENGTH(8)] = {
    0x00, 0x00, 0x00, 0x80, 0x00, 0x00, 0x00, 0x00
};
static const tImage Arial_0x2e = { image_data_Arial_0x2e,
    0, 0, 8};

static const uint8_t image_data_Arial_0x2f[FIX_ZERO_LENGTH(8)] = {
    0x00, 0x80, 0x40, 0x30, 0x08, 0x04, 0x00, 0x00
};
static const tImage Arial_0x2f = { image_data_Arial_0x2f,
    0, 0, 8};

static const uint8_t image_data_Arial_0x30[FIX_ZERO_LENGTH(8)] = {
    0x00, 0x7c, 0xa2, 0x92, 0x8a, 0x7c, 0x00, 0x00
};
static const tImage Arial_0x30 = { image_data_Arial_0x30,
    0, 0, 8};

static const uint8_t image_data_Arial_0x31[FIX_ZERO_LENGTH(8)] = {
    0x00, 0x04, 0x02, 0xfe, 0x00, 0x00, 0x00, 0x00
};
static const tImage Arial_0x31 = { image_data_Arial_0x31,
    0, 0, 8};

static const uint8_t image_data_Arial_0x32[FIX_ZERO_LENGTH(8)] = {
    0x00, 0x84, 0xc2, 0xa2, 0x92, 0x8c, 0x00, 0x00
};
static const tImage Arial_0x32 = { image_data_Arial_0x32,
    0, 0, 8};

static const uint8_t image_data_Arial_0x33[FIX_ZERO_LENGTH(8)] = {
    0x00, 0x82, 0x92, 0x92, 0x9a, 0x64, 0x00, 0x00
};
static const tImage Arial_0x33 = { image_data_Arial_0x33,
    0, 0, 8};

static const uint8_t image_data_Arial_0x34[FIX_ZERO_LENGTH(8)] = {
    0x00, 0x60, 0x50, 0x4c, 0xfe, 0x40, 0x00, 0x00
};
static const tImage Arial_0x34 = { image_data_Arial_0x34,
    0, 0, 8};


static const uint8_t image_data_Arial_0x35[FIX_ZERO_LENGTH(8)] = {
    0x00, 0x5e, 0x8a, 0x8a, 0x8a, 0x72, 0x00, 0x00

};
static const tImage Arial_0x35 = { image_data_Arial_0x35,
    0, 0, 8};


static const uint8_t image_data_Arial_0x36[FIX_ZERO_LENGTH(8)] = {
    0x00, 0x7c, 0x8a, 0x8a, 0x8a, 0x72, 0x00, 0x00

};
static const tImage Arial_0x36 = { image_data_Arial_0x36,
    0, 0, 8};


static const uint8_t image_data_Arial_0x37[FIX_ZERO_LENGTH(8)] = {
    0x00, 0x02, 0x82, 0x62, 0x1e, 0x02, 0x00, 0x00

};
static const tImage Arial_0x37 = { image_data_Arial_0x37,
    0, 0, 8};


static const uint8_t image_data_Arial_0x38[FIX_ZERO_LENGTH(8)] = {
    0x00, 0x6c, 0x9a, 0x92, 0x9a, 0x64, 0x00, 0x00

};
static const tImage Arial_0x38 = { image_data_Arial_0x38,
    0, 0, 8};


static const uint8_t image_data_Arial_0x39[FIX_ZERO_LENGTH(8)] = {
    0x00, 0x9c, 0xa2, 0xa2, 0xa2, 0x7c, 0x00, 0x00

};
static const tImage Arial_0x39 = { image_data_Arial_0x39,
    0, 0, 8};


static const uint8_t image_data_Arial_0x3a[FIX_ZERO_LENGTH(8)] = {
    0x00, 0x00, 0x00, 0x88, 0x00, 0x00, 0x00, 0x00

};
static const tImage Arial_0x3a = { image_data_Arial_0x3a,
    0, 0, 8};


static const uint8_t image_data_Arial_0x3b[FIX_ZERO_LENGTH(8)] = {
    0x00, 0x00, 0x00, 0xc8, 0x00, 0x00, 0x00, 0x00


};
static const tImage Arial_0x3b = { image_data_Arial_0x3b,
    0, 0, 8};


static const uint8_t image_data_Arial_0x3c[FIX_ZERO_LENGTH(8)] = {
    0x20, 0x20, 0x30, 0x50, 0x48, 0x88, 0x00, 0x00

};
static const tImage Arial_0x3c = { image_data_Arial_0x3c,
    0, 0, 8};


static const uint8_t image_data_Arial_0x3d[FIX_ZERO_LENGTH(8)] = {
    0x00, 0x28, 0x28, 0x28, 0x28, 0x28, 0x00, 0x00

};
static const tImage Arial_0x3d = { image_data_Arial_0x3d,
    0, 0, 8};


static const uint8_t image_data_Arial_0x3e[FIX_ZERO_LENGTH(8)] = {
    0x00, 0x88, 0x48, 0x50, 0x30, 0x20, 0x00, 0x00

};
static const tImage Arial_0x3e = { image_data_Arial_0x3e,
    0, 0, 8};


static const uint8_t image_data_Arial_0x3f[FIX_ZERO_LENGTH(8)] = {
    0x00, 0x04, 0x02, 0xa2, 0x12, 0x0c, 0x00, 0x00

};
static const tImage Arial_0x3f = { image_data_Arial_0x3f,
    0, 0, 8};


static const uint8_t image_data_Arial_0x40[FIX_ZERO_LENGTH(8)] = {
    0x38, 0x44, 0x92, 0xaa, 0xaa, 0xbc, 0x00, 0x00

};
static const tImage Arial_0x40 = { image_data_Arial_0x40,
    0, 0, 8};


static const uint8_t image_data_Arial_0x41[FIX_ZERO_LENGTH(8)] = {
    0x80, 0x60, 0x38, 0x26, 0x38, 0xc0, 0x80, 0x00

};
static const tImage Arial_0x41 = { image_data_Arial_0x41,
    0, 0, 8};


static const uint8_t image_data_Arial_0x42[FIX_ZERO_LENGTH(8)] = {
    0x00, 0xfe, 0x92, 0x92, 0x92, 0xec, 0x00, 0x00

};
static const tImage Arial_0x42 = { image_data_Arial_0x42,
    0, 0, 8};


static const uint8_t image_data_Arial_0x43[FIX_ZERO_LENGTH(8)] = {
    0x00, 0x7c, 0x82, 0x82, 0x82, 0xc6, 0x00, 0x00

};
static const tImage Arial_0x43 = { image_data_Arial_0x43,
    0, 0, 8};


static const uint8_t image_data_Arial_0x44[FIX_ZERO_LENGTH(8)] = {
    0x00, 0xfe, 0x82, 0x82, 0x82, 0x7c, 0x00, 0x00

};
static const tImage Arial_0x44 = { image_data_Arial_0x44,
    0, 0, 8};


static const uint8_t image_data_Arial_0x45[FIX_ZERO_LENGTH(8)] = {
    0x00, 0xfe, 0x92, 0x92, 0x92, 0x82, 0x00, 0x00

};
static const tImage Arial_0x45 = { image_data_Arial_0x45,
    0, 0, 8};


static const uint8_t image_data_Arial_0x46[FIX_ZERO_LENGTH(8)] = {
    0x00, 0xfe, 0x12, 0x12, 0x12, 0x02, 0x00, 0x00

};
static const tImage Arial_0x46 = { image_data_Arial_0x46,
    0, 0, 8};


static const uint8_t image_data_Arial_0x47[FIX_ZERO_LENGTH(8)] = {
    0x38, 0x44, 0x82, 0x82, 0xa2, 0xe4, 0x00, 0x00

};
static const tImage Arial_0x47 = { image_data_Arial_0x47,
    0, 0, 8};


static const uint8_t image_data_Arial_0x48[FIX_ZERO_LENGTH(8)] = {
    0x00, 0xfe, 0x10, 0x10, 0x10, 0xfe, 0x00, 0x00

};
static const tImage Arial_0x48 = { image_data_Arial_0x48,
    0, 0, 8};


static const uint8_t image_data_Arial_0x49[FIX_ZERO_LENGTH(8)] = {
    0x00, 0x82, 0x82, 0xfe, 0x82, 0x00, 0x00, 0x00

};
static const tImage Arial_0x49 = { image_data_Arial_0x49,
    0, 0, 8};


static const uint8_t image_data_Arial_0x4a[FIX_ZERO_LENGTH(8)] = {
    0x00, 0x80, 0x82, 0x82, 0x7e, 0x02, 0x00, 0x00

};
static const tImage Arial_0x4a = { image_data_Arial_0x4a,
    0, 0, 8};


static const uint8_t image_data_Arial_0x4b[FIX_ZERO_LENGTH(8)] = {
    0x00, 0xfe, 0x18, 0x24, 0x44, 0x82, 0x00, 0x00

};
static const tImage Arial_0x4b = { image_data_Arial_0x4b,
    0, 0, 8};


static const uint8_t image_data_Arial_0x4c[FIX_ZERO_LENGTH(8)] = {
    0x00, 0xfe, 0x80, 0x80, 0x80, 0x80, 0x00, 0x00

};
static const tImage Arial_0x4c = { image_data_Arial_0x4c,
    0, 0, 8};


static const uint8_t image_data_Arial_0x4d[FIX_ZERO_LENGTH(8)] = {
    0x00, 0xfe, 0x18, 0x30, 0x08, 0xfe, 0x00, 0x00

};
static const tImage Arial_0x4d = { image_data_Arial_0x4d,
    0, 0, 8};


static const uint8_t image_data_Arial_0x4e[FIX_ZERO_LENGTH(8)] = {
    0x00, 0xfe, 0x08, 0x10, 0x60, 0xfe, 0x00, 0x00

};
static const tImage Arial_0x4e = { image_data_Arial_0x4e,
    0, 0, 8};


static const uint8_t image_data_Arial_0x4f[FIX_ZERO_LENGTH(8)] = {
    0x38, 0x44, 0x82, 0x82, 0x82, 0x7c, 0x00, 0x00

};
static const tImage Arial_0x4f = { image_data_Arial_0x4f,
    0, 0, 8};


static const uint8_t image_data_Arial_0x50[FIX_ZERO_LENGTH(8)] = {
    0x00, 0xfe, 0x12, 0x12, 0x12, 0x0c, 0x00, 0x00

};
static const tImage Arial_0x50 = { image_data_Arial_0x50,
    0, 0, 8};


static const uint8_t image_data_Arial_0x51[FIX_ZERO_LENGTH(8)] = {
    0x38, 0xc4, 0x82, 0x02, 0x82, 0x7c, 0x00, 0x00


};
static const tImage Arial_0x51 = { image_data_Arial_0x51,
    0, 0, 8};


static const uint8_t image_data_Arial_0x52[FIX_ZERO_LENGTH(8)] = {
    0x00, 0xfe, 0x12, 0x12, 0x72, 0x8c, 0x00, 0x00

};
static const tImage Arial_0x52 = { image_data_Arial_0x52,
    0, 0, 8};


static const uint8_t image_data_Arial_0x53[FIX_ZERO_LENGTH(8)] = {
    0x00, 0xcc, 0x8a, 0x92, 0x92, 0x64, 0x00, 0x00

};
static const tImage Arial_0x53 = { image_data_Arial_0x53,
    0, 0, 8};


static const uint8_t image_data_Arial_0x54[FIX_ZERO_LENGTH(8)] = {
    0x02, 0x02, 0x02, 0xfe, 0x02, 0x02, 0x00, 0x00

};
static const tImage Arial_0x54 = { image_data_Arial_0x54,
    0, 0, 8};


static const uint8_t image_data_Arial_0x55[FIX_ZERO_LENGTH(8)] = {
    0x00, 0x7e, 0x80, 0x80, 0x80, 0x7e, 0x00, 0x00

};
static const tImage Arial_0x55 = { image_data_Arial_0x55,
    0, 0, 8};


static const uint8_t image_data_Arial_0x56[FIX_ZERO_LENGTH(8)] = {
    0x02, 0x0c, 0x70, 0xc0, 0x30, 0x0e, 0x00, 0x00

};
static const tImage Arial_0x56 = { image_data_Arial_0x56,
    0, 0, 8};


static const uint8_t image_data_Arial_0x57[FIX_ZERO_LENGTH(8)] = {
    0x06, 0xf8, 0x30, 0x0c, 0x70, 0xfc, 0x02, 0x00

};
static const tImage Arial_0x57 = { image_data_Arial_0x57,
    0, 0, 8};


static const uint8_t image_data_Arial_0x58[FIX_ZERO_LENGTH(8)] = {
    0x00, 0xc2, 0x2c, 0x10, 0x6c, 0x82, 0x00, 0x00

};
static const tImage Arial_0x58 = { image_data_Arial_0x58,
    0, 0, 8};


static const uint8_t image_data_Arial_0x59[FIX_ZERO_LENGTH(8)] = {
    0x02, 0x06, 0x08, 0xf0, 0x08, 0x06, 0x00, 0x00

};
static const tImage Arial_0x59 = { image_data_Arial_0x59,
    0, 0, 8};


static const uint8_t image_data_Arial_0x5a[FIX_ZERO_LENGTH(8)] = {
    0x00, 0xc2, 0xa2, 0x92, 0x8e, 0x82, 0x00, 0x00

};
static const tImage Arial_0x5a = { image_data_Arial_0x5a,
    0, 0, 8};


static const uint8_t image_data_Arial_0x5b[FIX_ZERO_LENGTH(8)] = {
    0x00, 0x00, 0xfe, 0x02, 0x02, 0x02, 0x00, 0x00

};
static const tImage Arial_0x5b = { image_data_Arial_0x5b,
    0, 0, 8};


static const uint8_t image_data_Arial_0x5c[FIX_ZERO_LENGTH(8)] = {
    0x00, 0x04, 0x18, 0x20, 0xc0, 0x80, 0x00, 0x00

};
static const tImage Arial_0x5c = { image_data_Arial_0x5c,
    0, 0, 8};


static const uint8_t image_data_Arial_0x5d[FIX_ZERO_LENGTH(8)] = {
    0x00, 0x02, 0x02, 0x02, 0xfe, 0x00, 0x00, 0x00


};
static const tImage Arial_0x5d = { image_data_Arial_0x5d,
    0, 0, 8};


static const uint8_t image_data_Arial_0x5e[FIX_ZERO_LENGTH(8)] = {
    0x00, 0x08, 0x04, 0x02, 0x0c, 0x00, 0x00, 0x00

};
static const tImage Arial_0x5e = { image_data_Arial_0x5e,
    0, 0, 8};


static const uint8_t image_data_Arial_0x5f[FIX_ZERO_LENGTH(8)] = {
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01


};
static const tImage Arial_0x5f = { image_data_Arial_0x5f,
    0, 0, 8};


static const uint8_t image_data_Arial_0x60[FIX_ZERO_LENGTH(8)] = {
    0x00, 0x00, 0x04, 0x04, 0x00, 0x00, 0x00, 0x00

};
static const tImage Arial_0x60 = { image_data_Arial_0x60,
    0, 0, 8};


static const uint8_t image_data_Arial_0x61[FIX_ZERO_LENGTH(8)] = {
    0x00, 0xc8, 0xa8, 0xa8, 0xa8, 0xf0, 0x00, 0x00

};
static const tImage Arial_0x61 = { image_data_Arial_0x61,
    0, 0, 8};


static const uint8_t image_data_Arial_0x62[FIX_ZERO_LENGTH(8)] = {
    0x00, 0xfe, 0x88, 0x88, 0x88, 0x70, 0x00, 0x00

};
static const tImage Arial_0x62 = { image_data_Arial_0x62,
    0, 0, 8};


static const uint8_t image_data_Arial_0x63[FIX_ZERO_LENGTH(8)] = {
    0x00, 0x70, 0x88, 0x88, 0x88, 0x98, 0x00, 0x00

};
static const tImage Arial_0x63 = { image_data_Arial_0x63,
    0, 0, 8};


static const uint8_t image_data_Arial_0x64[FIX_ZERO_LENGTH(8)] = {
    0x00, 0x70, 0x88, 0x88, 0x88, 0xfe, 0x00, 0x00

};
static const tImage Arial_0x64 = { image_data_Arial_0x64,
    0, 0, 8};


static const uint8_t image_data_Arial_0x65[FIX_ZERO_LENGTH(8)] = {
    0x00, 0x70, 0xa8, 0xa8, 0xa8, 0xb0, 0x00, 0x00

};
static const tImage Arial_0x65 = { image_data_Arial_0x65,
    0, 0, 8};


static const uint8_t image_data_Arial_0x66[FIX_ZERO_LENGTH(8)] = {
    0x00, 0x08, 0xfe, 0x0a, 0x0a, 0x02, 0x00, 0x00

};
static const tImage Arial_0x66 = { image_data_Arial_0x66,
    0, 0, 8};


static const uint8_t image_data_Arial_0x67[FIX_ZERO_LENGTH(8)] = {
    0x00, 0xf8, 0xc8, 0xc8, 0xb8, 0x08, 0x00, 0x01


};
static const tImage Arial_0x67 = { image_data_Arial_0x67,
    0, 0, 8};


static const uint8_t image_data_Arial_0x68[FIX_ZERO_LENGTH(8)] = {
    0x00, 0xfe, 0x08, 0x08, 0x08, 0xf0, 0x00, 0x00

};
static const tImage Arial_0x68 = { image_data_Arial_0x68,
    0, 0, 8};


static const uint8_t image_data_Arial_0x69[FIX_ZERO_LENGTH(8)] = {
    0x00, 0x88, 0x88, 0xfa, 0x80, 0x00, 0x00, 0x00

};
static const tImage Arial_0x69 = { image_data_Arial_0x69,
    0, 0, 8};


static const uint8_t image_data_Arial_0x6a[FIX_ZERO_LENGTH(8)] = {
    0x00, 0x00, 0x08, 0x08, 0xfa, 0x00, 0x00, 0x00


};
static const tImage Arial_0x6a = { image_data_Arial_0x6a,
    0, 0, 8};


static const uint8_t image_data_Arial_0x6b[FIX_ZERO_LENGTH(8)] = {
    0x00, 0xfe, 0x20, 0x30, 0x48, 0x88, 0x00, 0x00

};
static const tImage Arial_0x6b = { image_data_Arial_0x6b,
    0, 0, 8};


static const uint8_t image_data_Arial_0x6c[FIX_ZERO_LENGTH(8)] = {
    0x00, 0x82, 0x82, 0xfe, 0x80, 0x80, 0x00, 0x00

};
static const tImage Arial_0x6c = { image_data_Arial_0x6c,
    0, 0, 8};


static const uint8_t image_data_Arial_0x6d[FIX_ZERO_LENGTH(8)] = {
    0xf8, 0x08, 0x08, 0xf0, 0x08, 0xf8, 0x00, 0x00

};
static const tImage Arial_0x6d = { image_data_Arial_0x6d,
    0, 0, 8};


static const uint8_t image_data_Arial_0x6e[FIX_ZERO_LENGTH(8)] = {
    0x00, 0xf8, 0x08, 0x08, 0x08, 0xf0, 0x00, 0x00

};
static const tImage Arial_0x6e = { image_data_Arial_0x6e,
    0, 0, 8};


static const uint8_t image_data_Arial_0x6f[FIX_ZERO_LENGTH(8)] = {
    0x00, 0x70, 0x88, 0x88, 0x88, 0x70, 0x00, 0x00

};
static const tImage Arial_0x6f = { image_data_Arial_0x6f,
    0, 0, 8};


static const uint8_t image_data_Arial_0x70[FIX_ZERO_LENGTH(8)] = {
    0x00, 0xf8, 0x88, 0x88, 0x88, 0x70, 0x00, 0x00


};
static const tImage Arial_0x70 = { image_data_Arial_0x70,
    0, 0, 8};


static const uint8_t image_data_Arial_0x71[FIX_ZERO_LENGTH(8)] = {
    0x00, 0x70, 0x88, 0x88, 0x88, 0xf8, 0x00, 0x00


};
static const tImage Arial_0x71 = { image_data_Arial_0x71,
    0, 0, 8};


static const uint8_t image_data_Arial_0x72[FIX_ZERO_LENGTH(8)] = {
    0x00, 0x00, 0xf8, 0x08, 0x08, 0x08, 0x00, 0x00

};
static const tImage Arial_0x72 = { image_data_Arial_0x72,
    0, 0, 8};


static const uint8_t image_data_Arial_0x73[FIX_ZERO_LENGTH(8)] = {
    0x00, 0xd8, 0xa8, 0xa8, 0xa8, 0x48, 0x00, 0x00

};
static const tImage Arial_0x73 = { image_data_Arial_0x73,
    0, 0, 8};


static const uint8_t image_data_Arial_0x74[FIX_ZERO_LENGTH(8)] = {
    0x00, 0x08, 0x7c, 0x88, 0x88, 0x80, 0x00, 0x00

};
static const tImage Arial_0x74 = { image_data_Arial_0x74,
    0, 0, 8};


static const uint8_t image_data_Arial_0x75[FIX_ZERO_LENGTH(8)] = {
    0x00, 0xf8, 0x80, 0x80, 0x80, 0xf8, 0x00, 0x00

};
static const tImage Arial_0x75 = { image_data_Arial_0x75,
    0, 0, 8};


static const uint8_t image_data_Arial_0x76[FIX_ZERO_LENGTH(8)] = {
    0x00, 0x18, 0x60, 0x80, 0x60, 0x18, 0x00, 0x00

};
static const tImage Arial_0x76 = { image_data_Arial_0x76,
    0, 0, 8};


static const uint8_t image_data_Arial_0x77[FIX_ZERO_LENGTH(8)] = {
    0x08, 0x70, 0xe0, 0x18, 0xe0, 0x70, 0x08, 0x00

};
static const tImage Arial_0x77 = { image_data_Arial_0x77,
    0, 0, 8};


static const uint8_t image_data_Arial_0x78[FIX_ZERO_LENGTH(8)] = {
    0x00, 0x88, 0x50, 0x20, 0x50, 0x88, 0x00, 0x00

};
static const tImage Arial_0x78 = { image_data_Arial_0x78,
    0, 0, 8};


static const uint8_t image_data_Arial_0x79[FIX_ZERO_LENGTH(8)] = {
    0x00, 0x18, 0x60, 0x80, 0x60, 0x18, 0x00, 0x02


};
static const tImage Arial_0x79 = { image_data_Arial_0x79,
    0, 0, 8};


static const uint8_t image_data_Arial_0x7a[FIX_ZERO_LENGTH(8)] = {
    0x00, 0x88, 0xc8, 0xa8, 0x98, 0x88, 0x00, 0x00

};
static const tImage Arial_0x7a = { image_data_Arial_0x7a,
    0, 0, 8};


static const uint8_t image_data_Arial_0x7b[FIX_ZERO_LENGTH(8)] = {
    0x00, 0x10, 0xee, 0x01, 0x01, 0x01, 0x00, 0x00


};
static const tImage Arial_0x7b = { image_data_Arial_0x7b,
    0, 0, 8};


static const uint8_t image_data_Arial_0x7c[FIX_ZERO_LENGTH(8)] = {
    0x00, 0x00, 0x00, 0xfe, 0x00, 0x00, 0x00, 0x00


};
static const tImage Arial_0x7c = { image_data_Arial_0x7c,
    0, 0, 8};


static const uint8_t image_data_Arial_0x7d[FIX_ZERO_LENGTH(8)] = {
    0x00, 0x01, 0x01, 0xef, 0x10, 0x10, 0x00, 0x00


};
static const tImage Arial_0x7d = { image_data_Arial_0x7d,
    0, 0, 8};


static const uint8_t image_data_Arial_0x7e[FIX_ZERO_LENGTH(8)] = {
    0x00, 0x10, 0x08, 0x08, 0x10, 0x18, 0x00, 0x00

};
static const tImage Arial_0x7e = { image_data_Arial_0x7e,
    0, 0, 8};


static const tChar Arial_array[] = {


  // character: ' '
  {0x20, &Arial_0x20, 0, 0, 7, 8},



  // character: '!'
  {0x21, &Arial_0x21, 0, 0, 7, 8},



  // character: '\"'
  {0x22, &Arial_0x22, 0, 0, 7, 8},



  // character: '#'
  {0x23, &Arial_0x23, 0, 0, 7, 8},



  // character: '$'
  {0x24, &Arial_0x24, 0, 0, 7, 8},



  // character: '%'
  {0x25, &Arial_0x25, 0, 0, 7, 8},



  // character: '&'
  {0x26, &Arial_0x26, 0, 0, 7, 8},



  // character: '\''
  {0x27, &Arial_0x27, 0, 0, 7, 8},



  // character: '('
  {0x28, &Arial_0x28, 0, 0, 7, 8},



  // character: ')'
  {0x29, &Arial_0x29, 0, 0, 7, 8},




  // character: '*'
  {0x2a, &Arial_0x2a, 0, 0, 7, 8},




  // character: '+'
  {0x2b, &Arial_0x2b, 0, 0, 7, 8},




  // character: ','
  {0x2c, &Arial_0x2c, 0, 0, 7, 8},




  // character: '-'
  {0x2d, &Arial_0x2d, 0, 0, 7, 8},




  // character: '.'
  {0x2e, &Arial_0x2e, 0, 0, 7, 8},




  // character: '/'
  {0x2f, &Arial_0x2f, 0, 0, 7, 8},




  // character: '0'
  {0x30, &Arial_0x30, 0, 0, 7, 8},




  // character: '1'
  {0x31, &Arial_0x31, 0, 0, 7, 8},




  // character: '2'
  {0x32, &Arial_0x32, 0, 0, 7, 8},




  // character: '3'
  {0x33, &Arial_0x33, 0, 0, 7, 8},




  // character: '4'
  {0x34, &Arial_0x34, 0, 0, 7, 8},




  // character: '5'
  {0x35, &Arial_0x35, 0, 0, 7, 8},




  // character: '6'
  {0x36, &Arial_0x36, 0, 0, 7, 8},




  // character: '7'
  {0x37, &Arial_0x37, 0, 0, 7, 8},




  // character: '8'
  {0x38, &Arial_0x38, 0, 0, 7, 8},




  // character: '9'
  {0x39, &Arial_0x39, 0, 0, 7, 8},




  // character: ':'
  {0x3a, &Arial_0x3a, 0, 0, 7, 8},




  // character: ';'
  {0x3b, &Arial_0x3b, 0, 0, 7, 8},



  // character: '<'
  {0x3c, &Arial_0x3c, 0, 0, 7, 8},



  // character: '='
  {0x3d, &Arial_0x3d, 0, 0, 7, 8},



  // character: '>'
  {0x3e, &Arial_0x3e, 0, 0, 7, 8},



  // character: '?'
  {0x3f, &Arial_0x3f, 0, 0, 7, 8},



  // character: '\@'
  {0x40, &Arial_0x40, 0, 0, 7, 8},



  // character: 'A'
  {0x41, &Arial_0x41, 0, 0, 7, 8},




  // character: 'B'
  {0x42, &Arial_0x42, 0, 0, 7, 8},




  // character: 'C'
  {0x43, &Arial_0x43, 0, 0, 7, 8},




  // character: 'D'
  {0x44, &Arial_0x44, 0, 0, 7, 8},




  // character: 'E'
  {0x45, &Arial_0x45, 0, 0, 7, 8},




  // character: 'F'
  {0x46, &Arial_0x46, 0, 0, 7, 8},




  // character: 'G'
  {0x47, &Arial_0x47, 0, 0, 7, 8},




  // character: 'H'
  {0x48, &Arial_0x48, 0, 0, 7, 8},




  // character: 'I'
  {0x49, &Arial_0x49, 0, 0, 7, 8},




  // character: 'J'
  {0x4a, &Arial_0x4a, 0, 0, 7, 8},




  // character: 'K'
  {0x4b, &Arial_0x4b, 0, 0, 7, 8},




  // character: 'L'
  {0x4c, &Arial_0x4c, 0, 0, 7, 8},




  // character: 'M'
  {0x4d, &Arial_0x4d, 0, 0, 7, 8},




  // character: 'N'
  {0x4e, &Arial_0x4e, 0, 0, 7, 8},




  // character: 'O'
  {0x4f, &Arial_0x4f, 0, 0, 7, 8},




  // character: 'P'
  {0x50, &Arial_0x50, 0, 0, 7, 8},




  // character: 'Q'
  {0x51, &Arial_0x51, 0, 0, 7, 8},




  // character: 'R'
  {0x52, &Arial_0x52, 0, 0, 7, 8},




  // character: 'S'
  {0x53, &Arial_0x53, 0, 0, 7, 8},




  // character: 'T'
  {0x54, &Arial_0x54, 0, 0, 7, 8},




  // character: 'U'
  {0x55, &Arial_0x55, 0, 0, 7, 8},




  // character: 'V'
  {0x56, &Arial_0x56, 0, 0, 7, 8},




  // character: 'W'
  {0x57, &Arial_0x57, 0, 0, 7, 8},




  // character: 'X'
  {0x58, &Arial_0x58, 0, 0, 7, 8},




  // character: 'Y'
  {0x59, &Arial_0x59, 0, 0, 7, 8},




  // character: 'Z'
  {0x5a, &Arial_0x5a, 0, 0, 7, 8},




  // character: '['
  {0x5b, &Arial_0x5b, 0, 0, 7, 8},




  // character: '\'
  {0x5c, &Arial_0x5c, 0, 0, 7, 8},




  // character: ']'
  {0x5d, &Arial_0x5d, 0, 0, 7, 8},




  // character: '^'
  {0x5e, &Arial_0x5e, 0, 0, 7, 8},




  // character: '_'
  {0x5f, &Arial_0x5f, 0, 0, 7, 8},




  // character: '`'
  {0x60, &Arial_0x60, 0, 0, 7, 8},




  // character: 'a'
  {0x61, &Arial_0x61, 0, 0, 7, 8},




  // character: 'b'
  {0x62, &Arial_0x62, 0, 0, 7, 8},




  // character: 'c'
  {0x63, &Arial_0x63, 0, 0, 7, 8},




  // character: 'd'
  {0x64, &Arial_0x64, 0, 0, 7, 8},




  // character: 'e'
  {0x65, &Arial_0x65, 0, 0, 7, 8},




  // character: 'f'
  {0x66, &Arial_0x66, 0, 0, 7, 8},




  // character: 'g'
  {0x67, &Arial_0x67, 0, 0, 7, 8},




  // character: 'h'
  {0x68, &Arial_0x68, 0, 0, 7, 8},




  // character: 'i'
  {0x69, &Arial_0x69, 0, 0, 7, 8},




  // character: 'j'
  {0x6a, &Arial_0x6a, 0, 0, 7, 8},




  // character: 'k'
  {0x6b, &Arial_0x6b, 0, 0, 7, 8},




  // character: 'l'
  {0x6c, &Arial_0x6c, 0, 0, 7, 8},




  // character: 'm'
  {0x6d, &Arial_0x6d, 0, 0, 7, 8},




  // character: 'n'
  {0x6e, &Arial_0x6e, 0, 0, 7, 8},




  // character: 'o'
  {0x6f, &Arial_0x6f, 0, 0, 7, 8},




  // character: 'p'
  {0x70, &Arial_0x70, 0, 0, 7, 8},




  // character: 'q'
  {0x71, &Arial_0x71, 0, 0, 7, 8},




  // character: 'r'
  {0x72, &Arial_0x72, 0, 0, 7, 8},




  // character: 's'
  {0x73, &Arial_0x73, 0, 0, 7, 8},




  // character: 't'
  {0x74, &Arial_0x74, 0, 0, 7, 8},




  // character: 'u'
  {0x75, &Arial_0x75, 0, 0, 7, 8},




  // character: 'v'
  {0x76, &Arial_0x76, 0, 0, 7, 8},




  // character: 'w'
  {0x77, &Arial_0x77, 0, 0, 7, 8},




  // character: 'x'
  {0x78, &Arial_0x78, 0, 0, 7, 8},




  // character: 'y'
  {0x79, &Arial_0x79, 0, 0, 7, 8},




  // character: 'z'
  {0x7a, &Arial_0x7a, 0, 0, 7, 8},




  // character: '{'
  {0x7b, &Arial_0x7b, 0, 0, 7, 8},




  // character: '|'
  {0x7c, &Arial_0x7c, 0, 0, 7, 8},




  // character: '}'
  {0x7d, &Arial_0x7d, 0, 0, 7, 8},




  // character: '~'
  {0x7e, &Arial_0x7e, 0, 0, 7, 8}


};


const tFont Arial = { 95, Arial_array };


#undef FIX_ZERO_LENGTH
